;;
;;
;; database tables
;;
;; after creating database tables, some of the tables are expected to have
;; data as they are lookup tables, such as locations, department,
;; divisions, categories, recycle_locations, etc. The software provides
;; the inteface for some of these. Other may need to be added directly
;;
   create table users(                                                             id mediumint unsigned not null auto_increment,                                  username     varchar(10) not null,                                              first_name     varchar(70),                                                     last_name     varchar(70) not null,                                             office_phone   varchar(50),                                                     role          enum('end_user','View','Edit','Edit:Admin'),                      primary key(id),                                                                unique(username)                                                                )engine=InnoDB;

	create table employees(                                                          id mediumint unsigned not null auto_increment,                                  external_id  mediumint unsigned,                                                username     varchar(30) not null,                                              first_name     varchar(70),                                                     last_name     varchar(70) not null,                                             office_phone   varchar(50),                                                     role          enum('end_user','admin','helpdesk_admin','helpdesk_teck'),        primary key(id),                                                                unique(username)                                                                )engine=InnoDB;

	  create table locations (                                                     	 id           mediumint unsigned not null auto_increment,                        name         varchar(80),                                                       inactive    char(1),                                                            primary key(id)                                                                )engine=InnoDB;

	 create table recycle_locations (                                              	 id           tinyint unsigned not null auto_increment,                          name         varchar(80),                                                       inactive     char(1),                                                           primary key(id)                                                                 )engine=InnoDB;
					 
	 create table departments (                                                        id           mediumint unsigned not null auto_increment,                        name         varchar(50),                                                       inactive     char(1),                                                           primary key(id)                                                               )engine=InnoDB;					 
					 
	 create table divisions(                                                         id           mediumint unsigned not null auto_increment,                        dept_id      mediumint unsigned,                                                name         varchar(50),                                                       code    varchar(55),                                                            inactive  char(1),                                                              primary   key(id),                                                              foreign key(dept_id) references departments(id)                                 )engine=InnoDB;

		create table categories(                                                        id           mediumint unsigned not null auto_increment,                        name        varchar(80),                                                        inactive    char(1),                                                            primary key(id)                                                                 )engine=InnoDB;

	 insert into categories (id,name) values(1,'Computer'),(2,'Laptop'),(3,'NetworkPrinter'), (4,'UPS'),(5,'LCD 1'),(6,'LCD 2'),(7,'LCD 3'),(8,'LCD 4'),(9,'Scanner'),(10,'MacBook'),(11,'TV'),(12,'Projector'),(13,'External Hard Drive'),(14,'Docking Station'),(15,'Switch'),(16,'Plotter'),(17,'Copier'),(18,'Server'),(19,'Tablet'),(20,'SnmpDevice'),(21,'HttpDevice'),(22,'Unknown'),(23,'Other');


	 create table domains(                                                           id            tinyint unsigned not null auto_increment,                         name         varchar(70),                                                       inactive     char(1),                                                           primary key(id),                                                                index(name)                                                                     )engine=InnoDB;
;;
;; the following are City of Bloomington domains, change according to your
;; organization setup
;; 
	 
	 insert into domains (id,name) values(1,'COB'),(2,'City Hall'),(3,'Utilities'),(4,'Police'),(5,'Fire'),(6,'Blucher'),(7,'Dillman'),(8,'Monroe'),(9,'Transit')	 

	 create table devices(                                                            id              mediumint unsigned not null auto_increment,                     external_id     mediumint unsigned,                                             name            varchar(70),                                                    asset_num       varchar(20),                                                    serial_num      varchar(30),                                                    model      varchar(30),                                                         employee_id     mediumint unsigned,                                             description     varchar(30),                                                    category_id     mediumint unsigned,                                             received        date,                                                           age_length      tinyint,                                                        location_id     mediumint unsigned,                                             dept_id         mediumint unsigned,                                             domain_id       tinyint unsigned,                                               status          enum('Active','Donated','Auctioned','Recycled','Disposed'),                                                                                     processor       varchar(50),                                                    ram             varchar(30),                                                    hd_size         varchar(30),                                                    notes           text,                                                           mac_address     varchar(20),                                                    ip_address      varchar(20),                                                    editable        char(1),                                                        primary key(id),                                                                foreign key(category_id) references categories(id),                             foreign key(dept_id) references departments(id),                                foreign key(location_id) references locations(id),                              foreign key(employee_id) references employees(id),                              index(name, serial_num)                                                         )engine=InnoDB;	 
	
	 create table softwares(                                                          id            mediumint unsigned not null auto_increment,                       external_id   mediumint unsigned,                                               display_name varchar(70),                                                       vendor       varchar(70),                                                       installed         date,                                                         install_count int,                                                              editable      char(1),                                                          primary key(id),                                                                index(display_name)                                                             )engine=InnoDB;

					
 	 create table software_licenses(                                                 id            mediumint unsigned not null auto_increment,                       external_id   mediumint unsigned,                                               key_value     varchar(40),                                                      type          enum('IndividualLicense','VolumeLicense'),                        created       date,                                                             seat_limit    mediumint,                                                        editable      char(1),                                                          primary key(id)                                                                 )engine=InnoDB;


	 create table software_installations(                                            id          mediumint unsigned not null auto_increment,                         external_id mediumint unsigned,                                                 software_id mediumint unsigned,                                                 device_id   mediumint unsigned,                                                 license_id  mediumint unsigned,                                                 installed        date,                                                          editable    char(1),                                                            primary key(id),                                                                foreign key (device_id) references devices(id),                                 foreign key (software_id) references softwares(id),                             foreign key (license_id) references software_licenses(id)                       )engine=InnoDB;

	  create table discarded_items(                                                    id mediumint unsigned not null auto_increment,                                  item_id      mediumint unsigned not null,                                       type         enum('Device','Monitor','Printer','Other'),                        date         date,                                                              method       enum('Consumed','Discard','Lost'),                                 description  varchar(255),                                                      primary key(id)					                                                       )Engine=InnoDB;
					 

		create table auctions(                                                          id          mediumint unsigned not null auto_increment,                         name        varchar(70),                                                        date        date,                                                               primary key(id)                                                                 )engine=InnoDB;



    create table organizations(                                                     id          mediumint unsigned not null auto_increment,                         name        varchar(70),                                                        inactive    char(1),                                                             address     varchar(80),                                                        city        varchar(80),                                                        state       char(2),                                                            zip         varchar(15),                                                        contact     varchar(80),                                                        phone       varchar(50),                                                        primary key(id)                                                                )engine=InnoDB;		 

		 create table auction_items(                                                     id       mediumint unsigned not null auto_increment,                            auction_id mediumint unsigned not null,                                         asset_id    mediumint unsigned not null,                                        type       enum('Device','Monitor','Printer','Other'),                          value       decimal(7,2),                                                       description varchar(255),                                                       primary key(id),                                                                foreign    key(auction_id) references auctions(id)                             )engine=InnoDB;

  	 create table donations(                                                         id    mediumint unsigned not null auto_increment,                               organization_id       mediumint unsigned not null,                              asset_id         mediumint unsigned not null,                                    type enum('Device','Monitor','Printer','Other'),                                date            date,                                                           value           decimal(7,2),                                                   primary key(id),                                                                foreign key(organization_id) references organizations(id)                       )engine=InnoDB;

		 create table device_history(                                                      id          mediumint unsigned not null auto_increment,                         device_id mediumint unsigned not null,                                          status  enum('Active','Auctioned','Donated','Disposed','Recycled'),            date  date,                                                                     updater_id mediumint unsigned,                                                    primary key(id),                                                                foreign key(device_id) references devices(id),                                  foreign key(updater_id) references users(id)                                   )engine=InnoDB;
	  
		 create table recycled_items(                                                      id mediumint unsigned not null auto_increment,                                  location_id  tinyint unsigned,                                                  asset_id      mediumint unsigned,                                                type         enum('Device','Monitor','Printer','Other'),                        date         date,                                                              weight      decimal(8,2),                                                       description varchar(255),                                                       primary     key(id),                                                            foreign     key(location_id) references recycle_locations(id)                 )engine=InnoDB;

		 	create table data_imports(                                                       id mediumint unsigned not null auto_increment,                                  date         date,                                                              primary key(id)                                                                )engine=InnoDB;
				 
			 create table monitors(                                                           id              mediumint unsigned not null auto_increment,                     external_id     mediumint unsigned,                                             device_id       mediumint unsigned,                                             name            varchar(100),                                                   asset_num       varchar(20),                                                    serial_num      varchar(100),                                                   screen_size     tinyint,                                                        model           varchar(100),                                                   type           varchar(100),                                                    vertical_resolution tinyint,                                                    horizontal_resolution tinyint,                                                  manufacturer     varchar(100),                                                  received        date,                                                           expected_age    tinyint,                                                        status       enum('Active','Auctioned','Donated','Recycled','Disposed'),                                                                                        notes        varchar(255),                                                      editable     char(1),                                                           primary key(id),                                                                foreign key(device_id) references devices(id),                                  index(name, serial_num,asset_num)                                               )engine=InnoDB;

			 create table printers(                                                           id              mediumint unsigned not null auto_increment,                     external_id     mediumint unsigned,                                             name            varchar(70),                                                    device_id       mediumint,                                                      print_processor varchar(30),                                                    description     varchar(70),                                                    date            date,                                                           status          enum('Active','Donated','Auctioned','Recycled','Disposed'),                                                                                     notes           varchar(255),                                                   editable        char(1),                                                        primary key(id),                                                               index (name, print_processor, description)                                      )engine=InnoDB;

 			 create table attachments (                                                       id mediumint unsigned NOT NULL AUTO_INCREMENT,                                 file_name varchar(30) DEFAULT NULL,                                             old_file_name varchar(258) DEFAULT NULL,                                        obj_id mediumint unsigned DEFAULT NULL,                                         obj_type enum('Device','Printer','Monitor','Organization'),                     date date DEFAULT NULL,                                                         notes varchar(516) DEFAULT NULL,                                                user_id mediumint unsigned,                                                     PRIMARY KEY (id),                                                               foreign key(user_id) references users(id)                                       ) ENGINE=InnoDB;
